Default: &defaults
  database: charybdis.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: charybdis_test.sqlite3
  <<: *defaults

Staging:
  database: charybdis_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: charybdis_production.sqlite3
  poolsize: 100
  <<: *defaults
